# Generated by Django 3.1.7 on 2021-05-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='helpcenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(choices=[('forgotpassword', 'forgotpassword'), ('security', 'security')], max_length=100)),
                ('probdesc', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'queries',
            },
        ),
    ]
