# Generated by Django 3.2.3 on 2021-05-16 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='helpcenter',
        ),
    ]
