# Generated by Django 3.2.3 on 2021-05-16 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_helpcenter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HelpCenter',
        ),
    ]
