# Generated by Django 3.2.3 on 2021-05-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_helpcenter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tran_date', models.DateField()),
                ('tran_category', models.CharField(max_length=50, verbose_name='Enter Transaction Category')),
                ('credit_amount', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('debit_amount', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('description', models.CharField(max_length=100, verbose_name='Enter Description')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
    ]
