# Generated by Django 3.2.3 on 2021-05-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_transaction_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='credit_amount',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10, verbose_name='Credit Amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='debit_amount',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10, verbose_name='Debit Amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Transaction Description'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tran_category',
            field=models.CharField(max_length=50, verbose_name='Transaction Category'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tran_date',
            field=models.DateField(verbose_name='Transaction Date'),
        ),
    ]
